/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.AlumnoData;
import AccesoADatos.InscripcionData;
import Entidades.Alumno;
import Entidades.Inscripcion;
import Entidades.Materia;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nstut
 */
public class FormularioInscripciones extends javax.swing.JInternalFrame {
private DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form FormularionInscripciones
     */
    public FormularioInscripciones() {
        initComponents();
        agregarItems();
        armarCabecera();
        vaciarTabla();
        cargarNoInscriptas ();
        jtTablaMaterias.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcListaAlumnos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jrMatInsc = new javax.swing.JRadioButton();
        jrMatNoInsc = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaMaterias = new javax.swing.JTable();
        jbInscribir = new javax.swing.JButton();
        jbAnularInsc = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Formulario de Inscripciones");

        jLabel2.setText("Seleccione un alumno:");

        jcListaAlumnos.setToolTipText("");
        jcListaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcListaAlumnosActionPerformed(evt);
            }
        });

        jLabel3.setText("Listado de materias");

        jrMatInsc.setText("Materias inscriptas");
        jrMatInsc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrMatInscItemStateChanged(evt);
            }
        });
        jrMatInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMatInscActionPerformed(evt);
            }
        });

        jrMatNoInsc.setSelected(true);
        jrMatNoInsc.setText("Materias no inscriptas");
        jrMatNoInsc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrMatNoInscItemStateChanged(evt);
            }
        });
        jrMatNoInsc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jrMatNoInscStateChanged(evt);
            }
        });
        jrMatNoInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMatNoInscActionPerformed(evt);
            }
        });

        jtTablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jtTablaMaterias);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
        );

        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbAnularInsc.setText("Anular inscripcion");
        jbAnularInsc.setEnabled(false);
        jbAnularInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularInscActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jbInscribir)
                .addGap(18, 18, 18)
                .addComponent(jbAnularInsc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(jcListaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jrMatInsc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrMatNoInsc)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jcListaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrMatInsc)
                    .addComponent(jrMatNoInsc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbInscribir)
                        .addComponent(jbAnularInsc)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrMatInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMatInscActionPerformed

    }//GEN-LAST:event_jrMatInscActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        try{
            
            InscripcionData insc = new  InscripcionData(); //instanciamos los objetos que vamos a usar
            Alumno alumSelec = new  Alumno(); //intanciamos un alumno y una materia para llenarlos con los sellecionados en la lista de alumnos y en la tabla de materias
            Materia materiaSelec = new  Materia();//y posteriormente pasarlos por parametro a una inscripcion que vamos a instanciar


            alumSelec = (Alumno)jcListaAlumnos.getSelectedItem();

            Object[] fila = new Object[jtTablaMaterias.getColumnCount()]; //todo este codigo es para obtener los contenidos de la fila sellecionada de la tabla 
            for (int i = 0; i < jtTablaMaterias.getColumnCount();i++ ) { //y usarlos para setear los valores de los atributos de la materia instanciada antes
                fila[i] = jtTablaMaterias.getValueAt( jtTablaMaterias.getSelectedRow(), i);
            }
            materiaSelec.setIdMateria((int)fila[0]);
            materiaSelec.setNombre(fila[1].toString());
            materiaSelec.setAnioMateria((int)fila[2]);
            materiaSelec.setEstado(true);
            
            //una vez cargados los datos en el alumno instanciado y en la materia instanciada los pasamos a una inscripcion para crearla
            Inscripcion inscripcion = new Inscripcion(0,alumSelec,materiaSelec,0);
            insc.guardarInscripcion(inscripcion);//psamos la inscripcion como parametro al metodo que cargara los datos en la tabla
            
            vaciarTabla();
            cargarNoInscriptas();
            
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Debe seleccionar una materia.");
        }
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbAnularInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularInscActionPerformed
        try{   
            InscripcionData insc = new InscripcionData();
            Alumno alumSelec = (Alumno)jcListaAlumnos.getSelectedItem();
            int idAlum = alumSelec.getIdAlumno();
            int idMat = (int)jtTablaMaterias.getValueAt( jtTablaMaterias.getSelectedRow(), 0);
            insc.borrarInscripcion( idAlum,idMat);
            
            vaciarTabla();
            cargarInscriptas();
            
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Debe seleccionar una materia.");
        }
    }//GEN-LAST:event_jbAnularInscActionPerformed

    private void jcListaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcListaAlumnosActionPerformed
        if (jrMatNoInsc.isSelected()== true){
            vaciarTabla();
            cargarNoInscriptas();
        }else if (jrMatInsc.isSelected()== true){
            vaciarTabla();
            cargarInscriptas();
        }
    }//GEN-LAST:event_jcListaAlumnosActionPerformed

    private void jrMatNoInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMatNoInscActionPerformed

    }//GEN-LAST:event_jrMatNoInscActionPerformed

    private void jrMatNoInscStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jrMatNoInscStateChanged
        
        
    }//GEN-LAST:event_jrMatNoInscStateChanged

    private void jrMatNoInscItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrMatNoInscItemStateChanged
        vaciarTabla();
        if (jrMatNoInsc.isSelected() == true) {
            jrMatInsc.setSelected(false);
            
            jbInscribir.setEnabled(true);
            jbAnularInsc.setEnabled(false);
            cargarNoInscriptas();
        } else {
            jrMatInsc.setSelected(true);
            
            jbInscribir.setEnabled(false);
            jbAnularInsc.setEnabled(true);
        }
    }//GEN-LAST:event_jrMatNoInscItemStateChanged

    private void jrMatInscItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrMatInscItemStateChanged
        vaciarTabla();
        if (jrMatInsc.isSelected() == true) {
            jrMatNoInsc.setSelected(false);
            
            jbInscribir.setEnabled(false);
            jbAnularInsc.setEnabled(true);
            cargarInscriptas();
        } else {
            jrMatNoInsc.setSelected(true);
            
            jbInscribir.setEnabled(true);
            jbAnularInsc.setEnabled(false);
        }
    }//GEN-LAST:event_jrMatInscItemStateChanged

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed
   
    public void agregarItems (){
        AlumnoData alumData = new AlumnoData();
        List<Alumno> listaAlumnos = alumData.listarAlumnos();
        for (Alumno aux :listaAlumnos){
            jcListaAlumnos.addItem(aux);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnularInsc;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Alumno> jcListaAlumnos;
    private javax.swing.JRadioButton jrMatInsc;
    private javax.swing.JRadioButton jrMatNoInsc;
    private javax.swing.JTable jtTablaMaterias;
    // End of variables declaration//GEN-END:variables


private void armarCabecera(){
    model.addColumn("ID");
    model.addColumn("Nombre");
    model.addColumn("Año");
    jtTablaMaterias.setModel(model);
    
}
private void vaciarTabla () {
    for (int i = model.getRowCount()-1; i >=0;i--){
        model.removeRow(i);
    }
}

private void cargarInscriptas (){
        InscripcionData insc = new InscripcionData();
        Alumno alumnoSelec = (Alumno)jcListaAlumnos.getSelectedItem();

        List <Materia> listaInscriptas = insc.obtenerMateriasCursadas( alumnoSelec.getIdAlumno());

        for (Materia aux : listaInscriptas){
            model.addRow(new Object[]{aux.getIdMateria(),aux.getNombre(),aux.getAnioMateria()});
        }
}

private void cargarNoInscriptas (){
        InscripcionData insc = new InscripcionData();
        Alumno alumnoSelec = (Alumno)jcListaAlumnos.getSelectedItem();

        List <Materia> listaInscriptas = insc.obtenerMateriasNoCursadas( alumnoSelec.getIdAlumno());

        for (Materia aux : listaInscriptas){
            model.addRow(new Object[]{aux.getIdMateria(),aux.getNombre(),aux.getAnioMateria()});
        }
}
}