/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.MateriaData;
import Entidades.Materia;
import javax.swing.JOptionPane;
        
public class FormularioMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioMaterias
     */
    public FormularioMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfCod = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfAnio = new javax.swing.JTextField();
        jrEstado = new javax.swing.JRadioButton();
        jbBuscar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbModif = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 300));

        jLabel1.setText("Materias");

        jLabel2.setText("Código:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Año:");

        jLabel5.setText("Estado:");

        jtfCod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfCodMouseClicked(evt);
            }
        });
        jtfCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodActionPerformed(evt);
            }
        });
        jtfCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCodKeyReleased(evt);
            }
        });

        jtfNombre.setEnabled(false);
        jtfNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNombreMouseClicked(evt);
            }
        });
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        jtfNombre.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtfNombrePropertyChange(evt);
            }
        });
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });

        jtfAnio.setEnabled(false);
        jtfAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfAnioMouseClicked(evt);
            }
        });
        jtfAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnioActionPerformed(evt);
            }
        });
        jtfAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfAnioKeyReleased(evt);
            }
        });

        jrEstado.setEnabled(false);
        jrEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrEstadoMouseClicked(evt);
            }
        });
        jrEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrEstadoActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbBuscarMouseClicked(evt);
            }
        });
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.setEnabled(false);
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbModif.setText("Modificar");
        jbModif.setEnabled(false);
        jbModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrEstado)
                        .addGap(257, 257, 257))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jtfCod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbBuscar))
                                        .addComponent(jtfNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(jbModif)
                                .addGap(112, 112, 112)
                                .addComponent(jBSalir)))
                        .addGap(0, 96, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrEstado)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jBSalir)
                    .addComponent(jbModif))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnioActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        MateriaData matData = new MateriaData();
        try{
        Materia materia = matData.buscarMateria(Integer.parseInt(jtfCod.getText()));
        if (!materia.getNombre().isEmpty()){
            jtfNombre.setText(materia.getNombre());
            jtfAnio.setText(Integer.toString(materia.getAnioMateria()));
            jrEstado.setSelected(materia.isEstado());
            jrEstado.setEnabled(true);
        } else {
            jtfCod.setText("");
            jtfNombre.setText("");
            jtfAnio.setText("");
            jrEstado.setSelected(false);
            
        }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe introducir un código numerico");
        } catch (NullPointerException ex){
            /*JOptionPane.showMessageDialog(null, "No existe la materia");*/
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        try{
            if (jtfNombre.getText().isEmpty() || jtfAnio.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No pueden haber campos vacíos.");
            } else {
                if (jtfNombre.getText().length()<=2) {
                    JOptionPane.showMessageDialog(this, "Nombre demasiado corto.");
                } else {
                    MateriaData matData = new MateriaData();
                    Materia materia = new Materia();

                    materia.setNombre(jtfNombre.getText());
                    materia.setAnioMateria(Integer.parseInt(jtfAnio.getText()));
                    materia.setEstado(jrEstado.isSelected());

                    matData.guardarMateria(materia);

                    jtfCod.setText("");
                    jtfNombre.setText("");
                    jtfAnio.setText("");
                    jrEstado.setSelected(false);
                }
                
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El año debe ser un número.");
        }
        
        
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifActionPerformed
        MateriaData matData = new MateriaData();
        Materia mat=new Materia();
        try {
        mat.setAnioMateria(Integer.parseInt(jtfAnio.getText()));
        mat.setNombre(jtfNombre.getText());
        mat.setEstado(jrEstado.isSelected());
        mat.setIdMateria(Integer.parseInt(jtfCod.getText()));
        matData.modificarMateria(mat);
        
        jtfCod.setText("");
        jtfNombre.setText("");
        jtfAnio.setText("");
        jrEstado.setSelected(false);
        } catch (Exception ex ) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos");
        
        }
    }//GEN-LAST:event_jbModifActionPerformed

    private void jtfCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jtfCodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfCodMouseClicked
        jbNuevo.setEnabled(false);
        jbModif.setEnabled(false);
        jtfCod.setEnabled(true);
        jbBuscar.setEnabled(true);
           
        jtfNombre.setEnabled(false);
        jtfAnio.setEnabled(false);
        jrEstado.setEnabled(false);
        
        
        
        /*jtfNombre.setText("");
        jtfAnio.setText("");
        jrEstado.setSelected(false);*/
       
        
        
    }//GEN-LAST:event_jtfCodMouseClicked

    private void jtfNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNombreMouseClicked
        jtfNombre.setEnabled(true);
        jtfAnio.setEnabled(true);
        jrEstado.setEnabled(true);
        
        jtfCod.setEnabled(false);
        jbBuscar.setEnabled(false);
        
        
    }//GEN-LAST:event_jtfNombreMouseClicked

    private void jtfAnioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfAnioMouseClicked
        if (jtfCod.getText().equals("")) {
            jbNuevo.setEnabled(true);  
        }   
        jtfNombre.setEnabled(true);
        jtfAnio.setEnabled(true);
        jrEstado.setEnabled(true);
        
        jtfCod.setEnabled(false);
        jbBuscar.setEnabled(false);
        
        permitirModificar();
    }//GEN-LAST:event_jtfAnioMouseClicked

    private void jrEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrEstadoActionPerformed
       
    }//GEN-LAST:event_jrEstadoActionPerformed

    private void jbBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBuscarMouseClicked
        jbNuevo.setEnabled(false);   
        jbModif.setEnabled(true);
        jtfCod.setEnabled(false);
        jrEstado.setEnabled(true);
        jtfAnio.setEnabled(true);
        jtfNombre.setEnabled(true);
    }//GEN-LAST:event_jbBuscarMouseClicked

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped

    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jtfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyPressed

    }//GEN-LAST:event_jtfNombreKeyPressed

    private void jtfNombrePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtfNombrePropertyChange
   
    }//GEN-LAST:event_jtfNombrePropertyChange

    private void jtfNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyReleased
        if (jtfCod.getText().equals("") && !jtfNombre.getText().equals("")) {
          jbNuevo.setEnabled(true);  
        }
        if (jtfNombre.getText().equals("")) {
           jbNuevo.setEnabled(false);
        }
        jbBuscar.setEnabled(false);
        permitirModificar();
    }//GEN-LAST:event_jtfNombreKeyReleased

    private void jtfAnioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAnioKeyReleased
        jbBuscar.setEnabled(false);
        permitirModificar();
    }//GEN-LAST:event_jtfAnioKeyReleased

    private void jtfCodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodKeyReleased
        jtfNombre.setEnabled(false);
        jtfAnio.setEnabled(false);
        jrEstado.setEnabled(false);
        
        jbBuscar.setEnabled(true);
        
        jtfNombre.setText("");
        jtfAnio.setText("");
        jrEstado.setSelected(false);
    }//GEN-LAST:event_jtfCodKeyReleased

    private void jrEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrEstadoMouseClicked
         if (jtfCod.getText().equals("")) {
            jbNuevo.setEnabled(true);  
        }   
        jtfNombre.setEnabled(true);
        jtfAnio.setEnabled(true);
        jrEstado.setEnabled(true);
        
        jtfCod.setEnabled(false);
        jbBuscar.setEnabled(false);
        
        permitirModificar();
    }//GEN-LAST:event_jrEstadoMouseClicked
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbModif;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JRadioButton jrEstado;
    private javax.swing.JTextField jtfAnio;
    private javax.swing.JTextField jtfCod;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
    private void permitirModificar() {
        if (jtfCod.getText().isEmpty()){
            jbModif.setEnabled(false);
            jbNuevo.setEnabled(true);
        } else {
            jbModif.setEnabled(true);
            jbNuevo.setEnabled(false);
        }
                
    }
}
